---
title: "pre-processing & eda"
author: "Thu Tran - s3879312"
date: "`r Sys.Date()`"
output: pdf_document
---


```{r libraries}
library(readxl)
library(tidyr)
library(dplyr)
library(tidyr)
library(readxl)
library(ggplot2)
library(shiny)
library(stringr)
```



```{r pre-process: Incidence & Mortality, source: https://www.cancervic.org.au/research/vcr}

# Incidence
df_case <- read_excel("../../data/raw/Melanoma-in-Victoria-1982-2021.xlsx", sheet = "Incidence", skip = 4)
# Filter for cases only and drop unnecessary columns
data_cases <- df_case %>% 
  filter(Measure == "Cases") %>% 
  select(Year, Sex, `0-4`:`85+`)
# Convert df_case to long format
data_long <- data_cases %>% 
  pivot_longer(cols = `0-4`:`85+`, names_to = "AgeGroup", values_to = "Cases")
# Save data_long to a CSV file
write.csv(data_long, file = "../www/cleaned-incidence-Melanoma-in-Victoria-1982-2021.csv", row.names = FALSE)
head(data_long)
unique_age_groups <- unique(data_long$AgeGroup)
unique_age_groups

# Mortality
df_mortality <- read_excel("../../data/raw/Melanoma-in-Victoria-1982-2021.xlsx", sheet = "Mortality", skip = 4)
# Convert from wide format to long format
mortality_data_long <- df_mortality %>%
  gather(`Age Group`, `Value`, `0-4`:`85+`) %>%
  filter(Measure != "Deaths") %>% # To visualize only Age specific rate
  select(-Measure, -`Total deaths`) %>%  # Exclude the "Total deaths" column since it contains all NA
  rename(
    AgeGroup = `Age Group`,     # Rename "Age Group" to "AgeGroup"
    CrudeRate = `Crude rate`    # Rename "Crude rate" to "CrudeRate"
  )
write.csv(mortality_data_long, file = "../www/cleaned-mortality-Melanoma-in-Victoria-1982-2021.csv", row.names = FALSE)
head(mortality_data_long)
unique_age_groups <- unique(mortality_data_long$AgeGroup)
unique_age_groups
```


```{r Melanoma Globally}
# Overall Melanoma Rates
overall <- data.frame(
  Rank = c("World", 1:10),
  Country = c("World", "Australia", "New Zealand", "Denmark", "The Netherlands", "Norway", "Sweden", "Switzerland", "Germany", "Slovenia", "Finland"),
  Number = c(324635, 16171, 2801, 2886, 8310, 2567, 4266, 3357, 31468, 735, 2090),
  ASR = c(3.4, 36.6, 31.6, 29.7, 27.0, 26.4, 23.3, 21.6, 20.5, 19.7, 19.5)
)
overall
# Melanoma Rates in Men
men <- data.frame(
  Rank = c("World", 1:10),
  Country = c("World", "Australia", "New Zealand", "The Netherlands", "Denmark", "Norway", "Switzerland", "Sweden", "Germany", "Slovenia", "Finland"),
  Number = c(173844, 9462, 1541, 4420, 1382, 1298, 1822, 2146, 17260, 379, 1090),
  ASR = c(3.8, 42.9, 34.8, 27.1, 26.2, 25.8, 22.8, 22.2, 21.1, 19.9, 19.5)
)
men
# Melanoma Rates in Women
women <- data.frame(
  Rank = c("World", 1:10),
  Country = c("World", "Denmark", "Australia", "New Zealand", "Norway", "The Netherlands", "Sweden", "Belgium", "Switzerland", "Germany", "Ireland"),
  Number = c(150791, 1504, 6709, 1260, 1269, 3890, 2120, 1951, 1535, 14208, 772),
  ASR = c(3.0, 33.6, 30.8, 28.9, 27.5, 27.4, 24.6, 22.6, 20.8, 20.4, 20.3)
)
women
write.csv(overall, "../www/overall_melanoma_rates.csv", row.names = FALSE)
write.csv(men, "../www/men_melanoma_rates.csv", row.names = FALSE)
write.csv(women, "../www/women_melanoma_rates.csv", row.names = FALSE)

```




```{r protection: https://ncci.canceraustralia.gov.au/prevention/sun-exposure/sunburn-and-sun-protection}
# Creating dataframes for adults and adolescents
adults <- data.frame(
  Category = c("2003-04", "2006-07", "2010-11", "2013-14", "2016-17"),
  Male = c(37.6, 42.8, 38.0, 42.5, 43.1),
  Female = c(44.5, 47.1, 47.2, 42.3, 48.3),
  Persons = c(40.7, 44.8, 42.1, 42.5, 45.4)
)

adolescents <- data.frame(
  Category = c("2003-04", "2006-07", "2010-11", "2013-14", "2016-17"),
  Male = c(35.4, 34.2, 25.1, 25.6, 37.9),
  Female = c(23.8, 15.7, 21.3, 23.3, 31.9),
  Persons = c(30.2, 25.1, 23.2, 24.3, 35.2)
)

# Combine adults and adolescents dataframes into one dataframe
combined_df <- rbind(
  cbind(Group = "Adults", adults),
  cbind(Group = "Adolescents", adolescents)
)

# Export the dataframe to sunburn_protection.csv with comments
comments <- c(
  "# Attribution: ©2023 Cancer Australia - https://ncci.canceraustralia.gov.au",
  "# Data sourced from Cancer Council Australia’s National Sun Protection Surveys.",
  "# Proportions over time were adjusted for age, sex, skin type and weather conditions relevant to respondents’ activities on the weekend.",
  "# Refer to ‘About the data’ for the methodology used to adjust and apply statistical weighting to the data."
)

write.csv(combined_df, "../www/protection.csv", row.names = FALSE)
```


```{r subburn: https://ncci.canceraustralia.gov.au/prevention/sun-exposure/sunburn-and-sun-protection}
# Creating dataframes for sunburn data in adults and adolescents
sunburn_adults <- data.frame(
  Category = c("2003-04", "2006-07", "2010-11", "2013-14", "2016-17"),
  Male = c(15.7, 11.9, 9.4, 11.9, 14.6),
  Female = c(11.3, 7.9, 5.2, 7.6, 8.2),
  Persons = c(13.5, 9.8, 7.2, 9.7, 11.3)
)

sunburn_adolescents <- data.frame(
  Category = c("2003-04", "2006-07", "2010-11", "2013-14", "2016-17"),
  Male = c(19.7, 24.8, 14.9, 19.3, 17.8),
  Female = c(19.4, 16.5, 11.5, 15.2, 13.5),
  Persons = c(19.5, 20.5, 13.2, 17.3, 15.6)
)

# Combine sunburn dataframes for adults and adolescents into one dataframe
combined_sunburn_df <- rbind(
  cbind(Group = "Adults", sunburn_adults),
  cbind(Group = "Adolescents", sunburn_adolescents)
)

# Export the dataframe to sunburn.csv with comments
sunburn_comments <- c(
  "# Data sourced from the Cancer Council Australia’s National Sun Protection Survey.",
  "# Proportions over time were adjusted for age, sex, and state/territory.",
  "# Refer to ‘About the data’ for the methodology and category definitions used."
)

write.csv(combined_sunburn_df, "../www/sunburn.csv", row.names = FALSE)
```

